version: '3.8'
services:
    mongodb:
        image: 'mongo'
        ports:
            - '27017:27017'

    graphapi:
        build: .
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
